# Generated by Django 3.1.6 on 2021-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoreliaEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('is_happened', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500, null=True)),
                ('value', models.IntegerField(blank=True, choices=[(1, '0-5 dni'), (2, '6-12 dni'), (3, '13-20 dni'), (4, '21-30 dni')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.IntegerField(blank=True, choices=[(0, 'Brak'), (1, 'Rzadko'), (2, 'Średnio'), (3, 'Często')], default=0, null=True)),
                ('common_symptom', models.BooleanField(default=False)),
            ],
        ),
    ]
